site_name: My Beautiful Dark Twisted Fantasy
nav:
  - Home: index.md
  - Who is Kanye? : kanye.md
  - Album Overview: album_overview.md
  - Tracks:
      - Dark Fantasy: tracks/dark_fantasy.md
      - Gorgeous: tracks/gorgeous.md
      - Power: tracks/power.md
      - All of the Lights: tracks/all_of_the_lights.md
      - Monster: tracks/monster.md
      - So Appalled: tracks/so_appalled.md
      - Devil in a New Dress: tracks/devil_in_a_new_dress.md
      - Runaway: tracks/runaway.md
      - Hell of a Life: tracks/hell_of_a_life.md
      - Blame Game: tracks/blame_game.md
      - Lost in the World: tracks/lost_in_the_world.md
      - Who Will Survive in America: tracks/who_will_survive_in_america.md
  - Gallery: gallery.md
  - Contact: contact.md
theme:
  name: material
  palette:
    primary: red
    accent: black
  font:
    text: 'Lora'
    code: 'Roboto Mono'
extra_css:
  - css/custom.css
extra_javascript:
  - js/custom.js
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kanyewest
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/kanyewest/

